# -*- coding: utf-8 -*-
"""lab01.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJ3bcahLVHJTrpm8-7B0iQedDhqjrhsG
"""

###################################################
# MC102 - Algoritmos e Programação de Computadores
# Laboratório 1 - Aritmética com Inteiros
# Nome: Hamilton Guimarães da Silva Junior
# RA: 292623
###################################################

a = int(input())
b = int(input())

print("a =", a)
print("b =", b)
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a ** b =", a ** b)
print("a // b =", a // b)
print("a % b =", a % b)